### ISSUE TITLE
service and node register/deregister do not use supplied acl_token

### ISSUE THREAD

**Issue by tokenrain** [WeAreFarmGeek/diplomat#103]
It seems that a few Diplomat functions do not use the acl_token that is set during configuration.

Looking at the register method definition from service.rb

  def register(definition, path='/v1/agent/service/register')
      json_definition = JSON.dump(definition)
      register = @conn.put path, json_definition
      return register.status == 200
    end

I see that the acl_token definition is missing because it is neither part of query string not set as a http header. This means that service and node registrations/deregistartions can not happen when acls are in play using Diplomat. 

I have temporarily fixed this by modifying the register definition per below - but this may not be the most optimal way given the rest of the code flow

```
def register(definition, path='/v1/agent/service/register')
  path += "?#{check_acl_token[0]}" unless check_acl_token.empty?
  json_definition = JSON.dump(definition)
  register = @conn.put path, json_definition
  return register.status == 200
end
```

Most of the other put action use different syntax that adds the acl_token if it exists.

I was hoping this is something that you may want to fix and push push out a new gem. Thanks!

**Comment by tokenrain** [comment]
I am not sure how often you guys check these issue or when release cycles happen. I know you are not being paid for this. I was just wonder if you might be able to provide some base timeline as to when this issue might be looked at. All and any help is greatly appreciated.

**Comment by johnhamelink** [comment]
@tokenrain You are right that none of us are being paid to maintain this project - I started Diplomat a few years ago to fit a specific need I had on a project I was working on. I've long since completed that project and I no longer even write code in ruby day-to-day. As such, I maintain Diplomat as and when I can, and I can't commit to anything more specific than that!

@PeterFCaswell joined as a maintainer because he saw that this project wasn't moving as fast as it could be, and he had a lot to offer, so it made sense for him to join and contribute more directly.

If you are being paid to work on something that relies on diplomat, I'd recommend considering becoming a maintainer. Is that something you're interested in?

**Comment by taharah** [comment]
@johnhamelink I am highly interested in becoming a maintainer for this project as it is an essential component of a project that I am currently involved in.

**Comment by sixfeetover** [comment]
Try this: https://github.com/WeAreFarmGeek/diplomat/pull/160.

**Comment by tionebsalocin** [comment]
Token is now systematically managed and added in the http header for each calls.
If it exist in configuration or in the option object it will be send in the request.
https://github.com/WeAreFarmGeek/diplomat/blob/master/lib/diplomat/rest_client.rb#L179

**Comment by pierresouchay** [comment]
@tokenrain as explained by @tionebsalocin, the recent evolution of API now allow all kind of scenarii, including using a different token for each call without side effects. Feel free to reopen if you think we missed something
