### ISSUE TITLE
Using (or not) proxies with Diplomat

### ISSUE THREAD

**Issue by kuzmik** [WeAreFarmGeek/diplomat#15]
We have a weird situation in that we need to use a proxy for some traffic and not for other traffic. 

Diplomat (or farady in this case?) seems to pick up my ENV["HTTP_PROXY"] variables and is using that; I want diplomat to NOT use the proxy.

Is there a way to easily disable the proxy?

**Comment by johnhamelink** [comment]
Hey @kuzmik,

First of all, thanks for using diplomat! Thats an interesting use case, not something I've come across before. I'll take a look a little later to see if I can come up with a solution for you.

JH

**Comment by johnhamelink** [comment]
Hey @kuzmik 

Using Faraday on its own you can set a proxy as such:

````ruby
Faraday.new(:proxy => 'http://proxy.example.com:80')
Faraday.new(:proxy => {
  :uri      => 'http://proxy.example.com',
  :user     => 'foo',
  :password => 'bar'
})
```

Now I haven't tested this, but I'd be willing to bet that setting `:proxy` to `nil` would stop it using any proxy environment variable. Could you run a test where you try to run Faraday on its own and setting proxy to nil? If that works, I think we can make a fix for you to set your own parameters.

**Comment by kuzmik** [comment]
Sure, I will give it a whirl sometime today and let you know what happens!

**Comment by kuzmik** [comment]
Setting to nil doesn't do the trick... but setting it to '' does. Weird.

`[16] pry(main)> conn = Faraday.new(:url => 'https://localhost:30570', :proxy => nil).proxy
=> #<struct Faraday::ProxyOptions
 uri=#<URI::HTTP:0x00000002530b40 URL:http://webproxy.vip.sjc1.square:3128>,
 user=nil,
 password=nil>

[17] pry(main)> conn = Faraday.new(:url => 'http://localhost:30570', :proxy => '').proxy
=> #<struct Faraday::ProxyOptions uri=#<URI::Generic:0x0000000291cbc8 URL:>, user=nil, password=nil>
[18] pry(main)>`

**Comment by johnhamelink** [comment]
Hey @kuzmik sorry I didn't get back to this message - how rude of me!

It seems based on what you sent me that the issue is with Faraday, not with diplomat - if you find that's not the case please reopen this thread and I'll work with you to get the problem resolved.

Thanks!
JH

**Comment by literatesnow** [comment]
We have the same situation where Faraday is using ENV http_proxy (and ignoring ENV no_proxy) to connect to consul running on localhost via the proxy which results in HTTP 502's. Could we get Diplomat to force Faraday into not using the proxy?

**Comment by johnhamelink** [comment]
Hey @literatesnow! Looking through Faraday's Issues list, it seems like this PR will do exactly what you need: https://github.com/lostisland/faraday/pull/471. Because the issue is coming from Faraday, it needs to be fixed in Faraday in order for this to work.

I think the long-term goal to fix this should be to swap out Faraday with [Hurley](https://github.com/lostisland/hurley) as it seems to be under active maintenance. However that would be a breaking change for people who use Faraday's middlewares, and for that reason, we have to either wait until someone comes along with an adapter for Faraday middleware (not an unlikely thing to happen) or release a major and breaking revision.

In the meantime, you can use @kuzmik's findings (setting `:proxy => ''` in Faraday's connection) to query with the proxy explicitly turned off for consul. You might do it like this:

```ruby
@faraday = Faraday.new(:url => 'http://localhost:8500', :proxy => '')
@diplomat_kv = Diplomat::Kv.new(@faraday)
@diplomat_kv.get('lorem')
```

You could probably turn that idea into a wrapper class which you could use in the meantime to keep your code clean until this issue is fully resolved.

**Comment by literatesnow** [comment]
@johnhamelink Thanks very much for the workaround, I'll use it in the meantime (was missing the Diplomat::Kv.new part).
